site_name: approx
theme:
  name: "material"

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mkdocstrings

watch:
  - approx

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js