name: Publish to PyPI

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Run tests
      run: |
          poetry run pytest
    - name: Build wheels
      run: |
          poetry build
    - name: Publish Package
      run: |
        python -m poetry publish --username=${{ secrets.PYPIUSERNAME }} --password=${{ secrets.PYPIPASSWORD }}
